//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const FORGOTTEN_PASSWORD_REQUEST = "FORGOTTEN_PASSWORD_REQUEST";
export const FORGOTTEN_PASSWORD_FAILED = 'FORGOTTEN_PASSWORD_FAILED';
export const FORGOTTEN_PASSWORD_RESPONSE = 'FORGOTTEN_PASSWORD_RESPONSE';